server:
  port: 2223

spring:
  application:
    name : getwayServer

eureka:
  client:
    serviceUrl :
      defaultZone : http://localhost:1111/eureka/
#    fetchRegistry: false
#    registerWithEureka: false
zuul:
  routes:
    sysService:
      path : /sys/**
      serviceId : sysService
    xingjiService:
      path : /xingji/**
      serviceId : xingjiService
  debug:
    request: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
